- name: Configure Nodes
  hosts: all
  remote_user: sysadmin
  become: yes

  collections:
  - labrats_work.modules_ansible
  
  tasks:      
  - ansible.builtin.import_role:
      name: labrats_work.modules_ansible.containerd

  - ansible.builtin.import_role:
      name: labrats_work.modules_ansible.open_isci

  - ansible.builtin.import_role:
      name: labrats_work.modules_ansible.kubernetes_node
        
