
- name: Debug Master
  debug:
    var: master

- name: Debug Master Defaults
  debug:
    var: master_defaults
    
- name: Create Merged Dictionary
  ansible.builtin.set_fact: 
    kubernetes: "{{ master_defaults | combine(master_group) | combine(master) }}"

- name: Copy files for kubeadm init.
  ansible.builtin.template:
    src: "templates/kubeadm_init.yaml.j2"
    dest: /root/kubeadm_init.yaml
    owner: root
    group: root
    mode: '0600'

- name: Restart container runtime
  ansible.builtin.service:
    name: containerd
    state: restarted 

- name: Check for port 6443
  ansible.builtin.wait_for:
    port: 6443
    timeout: 10
    host: localhost
  register: port_check
  ignore_errors: yes

- name: Run kubeadm init.
  ansible.builtin.command: kubeadm init --config=/root/kubeadm_init.yaml --upload-certs
  when: port_check.failed == true

- name: Wait for port 6443 to become open on the host, don't start checking for 10 seconds
  ansible.builtin.wait_for:
    port: 6443
    delay: 10
    host: localhost
  when: port_check.failed == true

- name: Wait until the file /etc/kubernetes/admin.conf is present before continuing
  ansible.builtin.wait_for:
    path: /etc/kubernetes/admin.conf

- name: Create .kube directory
  ansible.builtin.file:
    path: .kube
    state: directory
    owner: sysadmin
    group: sysadmin
    mode: '0700'

- name: Copy admin.conf
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: sysadmin
    group: sysadmin
    mode: '0600'

- name: Copy files for calico init.
  become: no
  ansible.builtin.template:
    src: "templates/calico_init.yaml.j2"
    dest: calico_init.yaml
    owner: sysadmin
    group: sysadmin
    mode: '0600'

- name: Create tigera operator.
  become: no
  ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/tigera-operator.yaml
  ignore_errors: yes

- name: Run calico init.
  become: no
  ansible.builtin.command: kubectl apply -f calico_init.yaml
  ignore_errors: yes

- name: Get cluster_ca_data from master config file.
  ansible.builtin.shell: grep certificate-authority-data /etc/kubernetes/admin.conf | tr -d ' ' | cut -d ':' -f 2-
  register: grep_cluster_ca_data

- name: Get cluster_server from master config file.
  ansible.builtin.shell: grep server /etc/kubernetes/admin.conf | tr -d ' ' | cut -d ':' -f 2-
  register: grep_cluster_server

- name: Get kubeadm_token.
  ansible.builtin.shell: kubeadm token create
  register: kubeadm_token

- name: Set facts for join data.
  ansible.builtin.set_fact: 
    discovery:
      ca_data: "{{ grep_cluster_ca_data.stdout }}"
      server: "{{ grep_cluster_server.stdout }}"
      tlsBootstrapToken: "{{ kubeadm_token.stdout }}"
