---
# file: site.yml

- import_playbook: playbooks/hardening.yml
- import_playbook: playbooks/etc_hosts.yml
- import_playbook: playbooks/node.yml
- import_playbook: playbooks/master.yml
- import_playbook: playbooks/worker.yml
- import_playbook: playbooks/haproxy.yml
- import_playbook: playbooks/fluxcd.yml