name: 'Deploy Workspace'

on:
  workflow_dispatch:
    inputs:
      workspace:
        type: choice
        description: Workspace to use
        options: 
        - tomp736
      depsref:
        type: choice
        description: Repo deps ref
        options: 
        - main
        - dev
      lifetime:
        type: choice
        description: Lifetime of cluster (minutes).
        options:
        - 1m
        - 30m
        - 60m

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  RESOURCE_PREFIX: "${{ github.event.inputs.workspace }}-workspace-"

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    concurrency: 
      group: "${{ github.event.inputs.workspace }}-workspace-"
      cancel-in-progress: false      
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Create keypair for test.
      run: |
        ssh-keygen -t ed25519 -N '' -f id_ed25519
        xargs -a id_ed25519 -I{} -d'\n' echo ::add-mask::{}
        xargs -a id_ed25519.pub -I{} -d'\n' echo ::add-mask::{}
    - 
      name: Load keypair for test.
      run: |
        echo "Loading KEYFILE \"id_ed25519\" into GITHUB_ENV."
        echo 'KEYFILE<<EOF' >> $GITHUB_ENV
        cat id_ed25519 >> $GITHUB_ENV
        echo EOF >> $GITHUB_ENV

        echo "Loading PUBKEYFILE \"id_ed25519.pub\" into GITHUB_ENV."
        echo 'PUBKEYFILE<<EOF' >> $GITHUB_ENV
        cat id_ed25519.pub >> $GITHUB_ENV
        echo EOF >> $GITHUB_ENV
    - 
      name: Create default.tfvars file
      run: |
        echo "hcloud_token = \"${{ secrets.HCLOUD_TOKEN }}\"" >> default.tfvars
        echo "public_key = \"${{ env.PUBKEYFILE }}\"" >> default.tfvars
    - 
      name: Apply changes for remote backend
      run: |
        echo "Create default.tfrc file"
        echo "# default.tfrc" > default.tfrc
        echo "credentials \"app.terraform.io\" {" >> default.tfrc
        echo "  token = \"${{ secrets.TFCLOUD_TOKEN }}\"" >> default.tfrc
        echo "}" >> default.tfrc

        echo "Create config.remote.tfbackend"
        echo "# config.remote.tfbackend" > config.remote.tfbackend
        echo "workspaces { name = \"kubernetes_at_hetzner_${{ github.event.inputs.workspace }}\" }" >> config.remote.tfbackend
        echo "hostname     = \"app.terraform.io\"" >> config.remote.tfbackend
        echo "organization = \"labrats-work\"" >> config.remote.tfbackend 

        echo "Create config.remote.tfbackend"
        sed -i 's|local|remote|g' providers.tf
    - 
      name: Update prefix for resources.
      run: |
        sed -i 's|{prefix}|${{ env.RESOURCE_PREFIX }}|g' files/config.json
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: plan
        init: yes
        varsFile: default.tfvars
        planFile: tfplan
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      name: Terraform Apply
      uses: labrats-work/action-terraform@main
      with:
        verb: apply
        init: yes
        planFile: tfplan
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      name: Cache Ansible Collections
      uses: actions/cache@v3
      with:
        key: ansible-${{ env.BRANCH_NAME }}
        path: |
          ~/.ansible/collections
    - 
      name: Run playbook
      uses: labrats-work/action-ansible@main
      with:
        workingDirectory: ./ansible
    - 
      name: Cluster Timeout
      run: |
        echo "Will destroy cluster in ${{ github.event.inputs.lifetime }}."
        sleep ${{ github.event.inputs.lifetime }}
    - 
      if: always()
      continue-on-error: true
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: default.tfvars
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      if: always() && steps.destroy.outcome == 'failure'
      id: destroy2
      continue-on-error: true
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: default.tfvars
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      if: always() && steps.destroy2.outcome == 'failure'
      id: destroy3
      continue-on-error: true
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: default.tfvars
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    